{% set name = "ecape-parcel" %}
{% set version = "1.2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ecape_parcel-{{ version }}.tar.gz
  sha256: dab35709cc04774b4b2e80421907e52650505a5ee514c1954661ebdf73493f10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - ecape
    - metpy

test:
  imports:
    - ecape_parcel
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A simple Python package that computes entrainment CAPE parcels.
  dev_url: https://github.com/a-urq/ecape-parcel-py
  home: https://github.com/a-urq/ecape-parcel-py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
