{% set name = "ecape-parcel" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ecape_parcel-{{ version }}.tar.gz
  sha256: 081f32d412fcdd8f632c5959f81ca730277b81d58916b151a4dacbabe5e30fb8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - ecape
    - metpy
    - numpy
    - pint

test:
  files:
    - run_tests.sh
  commands:
    - sh run_tests.sh

about:
  summary: A simple Python package that computes entrainment CAPE parcels.
  dev_url: https://github.com/a-urq/ecape-parcel-py
  home: https://github.com/a-urq/ecape-parcel-py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
